keys:
  - &solio age1sg9f5uulpunc6ugcyrpenp49t3u34c4czr2g59ar6xwultupng8qlg79xe
  - &sierpe age1l5vsge04vuck7lk6rt2ms6z5crxek7rj7v3x02ulndht4qya8y9qxljse3
  - &eter age1h807c82a93e2qyhrd3thd664q0xrc8c8wfyzdplajpvzfpxejvksuu9sxx
  - &mora age1arpthm40s0rvmn0vs9k4meuc98h2pqzgk2wfkncf76ffef837c3sgezkhw
  - &bruma age1wy6w7hdvz65fhx24kyxkeaf02uhwf4anjkct260774ucal008yfq4dp5s0
  - &duende age1drdklq5804etwq266qh7pttzme55hf5junj27fmxhpx0ctsjlquqa3tdrt
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *solio
          - *sierpe
          - *eter
          - *mora
          - *bruma
          - *duende
