[colors]
background       = '#2b3e50'
black            = '#19242f'
blue             = '#5c98cd'
cursor           = '#f0cc04'
cyan             = '#8be0fd'
foreground       = '#F8F8F2'
green            = '#199c4b'
magenta          = '#ca94ff'
red              = '#e94b35'
tabs             = '#5c98cd'
tabs-active      = '#f0cc04'
white            = '#F8F8F2'
yellow           = '#f0cc04'
dim-black        = '#19242f'
dim-blue         = '#AE7BF8'
dim-cyan         = '#6fb3ca'
dim-foreground   = '#dfdfd9'
dim-green        = '#147c3c'
dim-magenta      = '#a176cc'
dim-red          = '#ba3c2a'
dim-white        = '#EFEFE1'
dim-yellow       = '#E6A003'
light-black      = '#2f3943'
light-blue       = '#D6ACFF'
light-cyan       = '#b9ecfd'
light-foreground = '#f8f8f2'
light-green      = '#72cc5a'
light-magenta    = '#d4a9ff'
light-red        = '#ff6541'
light-white      = '#FFFFFF'
light-yellow     = '#FFFFA5'
