[colors]
background = '#232136'
foreground = '#e0def4'
selection-background = '#44415a'
selection-foreground = '#e0def4'

cursor = '#e0def4'

tabs = '#232136'
tabs-active = '#393552'

black = '#393552'
red = '#eb6f92'
green = '#3e8fb0'
yellow = '#f6c177'
blue = '#9ccfd8'
magenta = '#c4a7e7'
cyan = '#ea9a97'
white = '#e0def4'

dim-black = '#6e6a86'
dim-red = '#eb6f92'
dim-green = '#3e8fb0'
dim-yellow = '#f6c177'
dim-blue = '#9ccfd8'
dim-magenta = '#c4a7e7'
dim-cyan = '#ea9a97'
dim-white = '#e0def4'

light-black = '#6e6a86'
light-red = '#eb6f92'
light-green = '#3e8fb0'
light-yellow = '#f6c177'
light-blue = '#9ccfd8'
light-magenta = '#c4a7e7'
light-cyan = '#ea9a97'
light-white = '#e0def4'
