# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["ahci" "xhci_pci" "sd_mod" "sdhci_pci"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7fdce164-d0d1-43c4-8bb0-7e48e4c83af7";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B8B2-C7D3";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/mnt/seclusium" = {
    device = "seclusium";
    fsType = "zfs";
  };

  fileSystems."/mnt/seclusium/echoes" = {
    device = "seclusium/echoes";
    fsType = "zfs";
  };

  fileSystems."/mnt/seclusium/dimensions" = {
    device = "seclusium/dimensions";
    fsType = "zfs";
  };

  fileSystems."/mnt/seclusium/creation" = {
    device = "seclusium/creation";
    fsType = "zfs";
  };

  fileSystems."/mnt/seclusium/technique" = {
    device = "seclusium/technique";
    fsType = "zfs";
  };

  fileSystems."/mnt/seclusium/imagery" = {
    device = "seclusium/imagery";
    fsType = "zfs";
  };

  fileSystems."/mnt/seclusium/zg" = {
    device = "seclusium/zg";
    fsType = "zfs";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/a55f8911-b16c-4fd1-a205-ee853d6873fb";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
