name: Build all Nix configurations
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

jobs:

  test_nixos_builds:
    name: Build NixOS configurations
    runs-on: ubuntu-latest
    container:
      image: nixos/nix:latest
      env:
        NIX_EXPERIMENTAL_FEATURES: "nix-command flakes"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/cachix-action@v12
        with:
          name: davsanchez
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build Darwin VM
        run: nixos-rebuild build --flake .#darwinVM
      - name: Build UTM VM
        run: nixos-rebuild build --flake .#nr-vm-utm

  test_darwin_builds:
    name: Build Darwin configurations
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v7
      - uses: cachix/cachix-action@v12
        with:
          name: davsanchez
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Install nix-darwin
        run: nix run nix-darwin -- switch --flake .#mbp
      - name: Build Darwin MBP
        run: darwin-rebuild build --flake .#mbp
      - name: Build Darwin Mini
        run: darwin-rebuild build --flake .#mini
    
  test_home_manager_builds:
    name: Build Home Manager configurations
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v7
      - uses: cachix/cachix-action@v12
        with:
          name: davsanchez
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Install home-manager
        run: nix run home-manager/master -- init --switch
      - name: Build Home Manager david@mbp
        if: ${{ matrix.os == 'macos-latest' }}
        run: home-manager build --flake ".#david@mbp"
      - name: Build Home Manager david@mini
        if: ${{ matrix.os == 'macos-latest' }}
        run: home-manager build --flake ".#david@mini"
      - name: Build Home Manager davidsanchez@nr-vm
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: home-manager build --flake ".#davidsanchez@nr-vm"
