name: CI
on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - master
      - renovate/**
  pull_request:
    branches:
      - master

jobs:
  linux:
    name: 🫧 Build Linux configs (eter)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Free up space
        run: bash .github/scripts/space_cleanup.sh
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v17
        with:
          name: davsanchez
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build NixOS config (eter)
        run: nix build ".#nixosConfigurations.eter.config.system.build.toplevel"

  linux-arm:
    name: 🫐 Build Linux configs (mora)
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - name: Free up space
        run: bash .github/scripts/space_cleanup.sh
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v17
        with:
          name: davsanchez
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build NixOS config (mora)
        run: nix build ".#nixosConfigurations.mora.config.system.build.toplevel"

  darwin-home-manager:
    name: 🍎 Build macOS configs (home-manager)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Free up space
        run: bash .github/scripts/space_cleanup.sh
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v17
        with:
          name: davsanchez
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      # - name: Check flake
      #   run: nix flake check -L
      - name: Build home-manager (solio)
        run: nix run home-manager -- build --flake ".#david@solio"
      - name: Build home-manager (sierpe)
        run: nix run home-manager -- build --flake ".#david@sierpe"

  check:
    name: 🟢 Decide whether the needed jobs succeeded or failed
    if: always()
    needs:
      - linux
      - linux-arm
      - darwin-home-manager
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
