name: Home Manager
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - renovate/**
    paths:
      - 'home/**'
      - 'flake.nix'
      - 'flake.lock'
      - '.github/workflows/home-manager.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'home/**'
      - 'flake.nix'
      - 'flake.lock'
      - '.github/workflows/home-manager.yml'

jobs:
  solio:
    name: 🍎 Build Home Manager (solio)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Free up space
        run: bash .github/scripts/space_cleanup.sh
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v17
        with:
          name: davsanchez
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build Home Manager (solio)
        run: nix run home-manager -- build --flake ".#david@solio"

  sierpe:
    name: 🍎 Build Home Manager (sierpe)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Free up space
        run: bash .github/scripts/space_cleanup.sh
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v17
        with:
          name: davsanchez
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build Home Manager (sierpe)
        run: nix run home-manager -- build --flake ".#david@sierpe"

  check:
    name: 🟢 Decide whether the needed jobs succeeded or failed
    if: always()
    needs:
      - solio
      - sierpe
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
