name: Update flake inputs
on:
  schedule:
    # 1st and 15th of each month at midnight UTC
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

jobs:

  update_flake_inputs:
    name: Update flake inputs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up git user
        run: |
          git config --global user.name 'DavSanchez's GitHub Actions'
          git config --global user.email 'DavSanchez+automation@users.noreply.github.com
      - name: Checkout a new branch
        run: git switch -c chore/update-flake-inputs
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v7
      - name: Update flake inputs
        run: nix flake update --commit-lock-file
      - name: Create Pull Request using GH CLI
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "chore: update flake inputs" --body "Update flake inputs"
      - name: Set branch for auto-merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --squash --auto --delete-branch
      
